src/clockview.mjs, src/initialisation.mjs, src/timekeeper.mjs, src/uipanel.mjs, styles/settings.css
and some minor cleanup to init code #80
=> moved uipanel init code into UIPanel class,

.github/workflows/main.yml
=> First draft of release action file

src/uipanel.mjs, templates/uipanel.hbs
=> Hiding UI controls for non-GM

.github/workflows/main.yml
=> test to see if the checkout version change works without further changes

.github/release-drafter.yml, .github/workflows/release-drafter.yml
#129
Using Release Drafter.
Hopefully this will make it easier to keep release notes up to date and informative.
=> GitHub Action to automate Change Log Creation

styles/easy-timekeeping.css
It now aligns exactly with the default Players panel. Fixes #134
=> Increased UI panel right margin by 1 pixel

lang/en.json
=> Changed no permission message to be more generic.

lang/en.json, lang/fr.json, src/initialisation.mjs, src/uipanel.mjs, styles/easy-timekeeping.css, templates/uipanel.hbs
As requested, I updated the UI so the fuzzy time shows the day when the exact time is hidden from players. I see these changes as temporary, since I'm planning to overhaul the UI with something more attractive in a future release.
=> 132 hiding time of day also hides the day counter

src/initialisation.mjs
=> Moving settings registration to the `i18nInit` hook.

src/uipanel.mjs
=> fixed integer arithmetic error in day and week calculation

lang/en.json, lang/fr.json, src/settings.mjs, src/uipanel.mjs, styles/easy-timekeeping.css, templates/uipanel.hbs
Controlled by a client setting, with values ranging from fully hidden to full opaque.
=> Added option to fade the UI when it's not being used

lang/fr.json
=> Updated French translation ## 0.8.0

README.md
=> Fixed broken workflow badges on GitHub readme

styles/easy-timekeeping.css
=> Added 2px gap between graphical clocks to improve visual appearance

src/uipanel.mjs
Made UI focus fade html manipulation more precise in all known edge cases.
fixes #182
=> Fixed broken UI fading after changing scenes

lang/en.json, lang/fr.json, src/settings.mjs, src/uipanel.mjs
=> Added client setting for including day in the exact time. By default, the day is not shown anymore. You can restore the old behaviour in the settings.

src/uipanel.mjs
=> Fixed regex exception when loading a world and changing the time

README.md
They should work now
fixes #195
=> Updated links in readme badges

README.md
=> Added latest release downloads badge

documentation/timekeeper.md, lang/en.json, lang/fr.json, src/constants.mjs, src/helpers.mjs, src/settings.mjs, src/timekeeper.mjs, src/timeteller.mjs, src/uipanel.mjs
I also updated the settings and JS Doc strings so it's clearer what they do. There was a surprising amount of refactoring with this change actually, some of it paving the way for future planned features.
=> Updated the long-format time display to include named days of the week

src/uipanel.mjs
Foundry is inconsistent in triggering a reload when AV setting changes are made, so I listen to the before and after AV setting hooks and detect when the dock location changes to manually trigger a Foundry reload.
fixes #178
=> Fixed UI disappearing when the AV Dock position is changed

templates/setTimeDialog.hbs
HTML newb mistake :)
fixes #213
=> Fixed Set Time validation bug that wouldn't let all times be set

README.md
=> Added open bugs badge. I aim to keep it at 0.

src/daylightcyclesettings.mjs, src/shiftsettings.mjs, src/weekdaysettings.mjs
=> Added Foundry default reminder about the Save Changes button being needed after using the Reset Defaults button on a settings form.

module.json
=> Added Sasmira to authors as thanks for all their work keeping the French translation up to date, bug fixes, testing, and ideas.

.github/workflows/release-drafter.yml
=> Added edited, labeled, & unlabeled types to release drafter workflow

README.md
=> Fixed contradictory text in readme.

lang/en.json, src/initialisation.mjs, src/settings.mjs, src/uipanel.mjs, styles/easy-timekeeping.css
As well as providing more options, this also helps fix a long-standing issue with the UI not displaying correctly on some browsers and when the Audio/Video mode is enabled.
=> Added optional floating UI panel which can be moved around on the canvas

src/initialisation.mjs
=> Fixed bug where UI did not appear when loading a world with no active scene.

lang/fr.json, styles/easy-timekeeping.css
- fix floatting window background color / font  / Color / sheme / padding
- french translation update
=> Fixed missing French translation strings, and fixed floating window background color to black.

module.json
=> Update module configuration to enable Italian language support.

CONTRIBUTING.md
Updated CONTRIBUTING.md with guidelines for translators and more clarity around focus in PRs
fixes #277
=> Updated Contribution guidelines with a section for translators and elaborated on the goal of focused pull requests.

src/uipanel.mjs
=> Reset time dialog is no longer modal.

lang/en.json, lang/fr.json, lang/it.json, src/settings.mjs, src/uipanel.mjs
=> Added client setting for floating ui panel opacity when it has focus.

.github/workflows/release-creation.yml
=> Adding names to unnamed workflow steps.

src/uipanel.mjs, styles/easy-timekeeping.css, templates/uipanel.hbs
=> UI should now remain the correct size while long text wraps to multiple lines.

module.json, src/packs/macros/macros_getPhaseOfDay_mFLZqXxvuxWE81zM.yml, src/packs/macros/macros_increment_A2dShvgSaIKQBON1.yml, src/packs/macros/macros_increment___no_arguments_I4pjnPXyQfv39Tys.yml, src/packs/macros/macros_increment___reduce_the_time_KUGnux9isV3D1TW7.yml, src/packs/macros/macros_set_1xtNC0iy6UtfGAoY.yml
=> Updating example macros & renaming compendium

src/daylightcycle.mjs
=> Added check for absence of scene in daylight cycle time change handler

src/packs/macros/folders_Time_Change_Handler_nL4GactRADbRkcfw.yml, src/packs/macros/macros_timeChangeHandler_aVzIsbEmo7cOq77U.yml
=> Adding example time change handler macro
